// Import file Global.css

import { faInstagram, faTiktok, faXTwitter } from "@/node_modules/@fortawesome/free-brands-svg-icons/index";
import { FontAwesomeIcon } from "@/node_modules/@fortawesome/react-fontawesome/index";
import Image from "@/node_modules/next/image";
import Link from "@/node_modules/next/link";
import "../app/globals.css"
import "@fortawesome/fontawesome-svg-core/styles.css"
import { faBars } from "@/node_modules/@fortawesome/free-solid-svg-icons/index";


export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  
  return (
    <html lang="en">
      <body>
        {/* Navbar */}
        <nav >
        <div className="navbar bg-blue-500 rounded">
            <div className="navbar-start">
              <div className="dropdown">
                <div tabIndex={0} role="button" className="btn btn-ghost btn-circle text-xl">
                  <FontAwesomeIcon icon={faBars} />
                </div>
                <ul
                  tabIndex={0}
                  className="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow">
                  <li>
                    <Link href={"/dashboard"}>
                      Dashboard
                    </Link>
                  </li>
                  <li>
                    <Link href={"/keranjang"}>
                      Keranjang
                    </Link>
                  </li>
                  <li>
                    <Link href={"/profil"}>
                      Profil
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
            <Link href={"/dashboard"} className="navbar-center btn btn-ghost text-xl">
              Barang Second
            </Link>
            <div className="navbar-end">
              <Link href="login">
                <button className="bg-white text-blue-500 px-4 py-2 rounded-md hover:bg-gray-200">
                  Login
                </button>
              </Link>
            </div>
          </div>
        </nav>

        {/* Header
        <header>
          <div className="relative h-72 w-full">
            <Image
              className="absolute inset-0 h-full w-full object-cover opacity-70"
              src={"/images/banner.png"}
              alt={"Banner Barang Second"}
              width={1851}
              height={222}
            />
          </div>
        </header> */}

        {/* Main Content */}
        <section className="m-5">
          {children}
        </section>

        {/* Footer */}
        <footer className="footer footer-center bg-blue-500 text-white rounded p-10">
          <nav className="grid grid-flow-col gap-4">
            <p>Follows Our Socials</p>
          </nav>
          <nav>
            <div className="grid grid-flow-col gap-4">
              <Link href="/" title="Instagram" >
                <FontAwesomeIcon icon={faInstagram} className="text-white mx-2 text-3xl" />
              </Link>
              <Link href="/" title="Tiktok" >
                <FontAwesomeIcon icon={faTiktok} className="text-white mx-2 text-3xl" />
              </Link>
              <Link href="/" title="Twitter" >
                <FontAwesomeIcon icon={faXTwitter} className="text-white mx-2 text-3xl" />
              </Link>
              
            </div>
          </nav>
          <aside>
            <p>Copyright ©2024 - Barang Second - Vanguard</p>
          </aside>
        </footer>
      </body>
    </html>
  );
}
