export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
      <body>
      <header>
        <div>
          test 123
        </div>
      </header>
      </body>
    </html>
  )
}
