// Import file Global.css
import Image from "next/image";
import "../app/globals.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Link from "next/link";
import { faInstagram } from "@fortawesome/free-brands-svg-icons";
import { faTiktok } from "@fortawesome/free-brands-svg-icons";
import { faXTwitter } from "@fortawesome/free-brands-svg-icons";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  
  return (
    <html lang="en">
      <body>
        {/* Navbar */}
        <nav className="flex justify-between items-center bg-blue-500 px-4 py-2">
          <div className="flex space-x-4">
          <a  href="/dashboard"
               className="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-blue-800 hover:text-white">
                Dashboard
              </a>
            
            <a href="/team"
               className="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-blue-800 hover:text-white">
                Team
              </a>
            
            <a href="/projects"
               className="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-blue-800 hover:text-white">
                Projects
              </a>
            
            <a href="/calendar"
               className="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-blue-800 hover:text-white">
                Calendar
              </a>
            
          </div>
          <div className="ml-auto">
            <a href="login">
              <button className="bg-white text-blue-500 px-4 py-2 rounded-md hover:bg-gray-200">
                Login
              </button>
              </a>
              
            
          </div>
        </nav>

        {/* Header */}
        <header>
          <div className="relative h-72 w-full">
            <Image
              className="absolute inset-0 h-full w-full object-cover opacity-70"
              src={"/images/banner.png"}
              alt={"Logo UTI"}
              width={1851}
              height={222}
            />
          </div>
        </header>

        {/* Main Content */}
        <section className="m-5">
          {children}
        </section>

        {/* Footer */}
        <footer className="bg-blue-500">
          <div className="text-center flex justify-center">Follow Our Socials</div>
          <div className="justify-center flex">
            <Link href="/" title="Instagram">
              <FontAwesomeIcon icon={faInstagram} className="text-white mx-2" />
            </Link>
            <Link href="/" title="Tiktok">
              <FontAwesomeIcon icon={faTiktok} className="text-white mx-2" />
            </Link>
            <Link href="/" title="Twitter">
              <FontAwesomeIcon icon={faXTwitter} className="text-white mx-2" />
            </Link>
          </div>
          <div className="text-white px-5 py-2.5 text-center flex justify-center">
            &copy; E-Katalog Barang Second 2024
          </div>
        </footer>
      </body>
    </html>
  );
}
